
[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x545862"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xc8ccd4"
yellow = "0xe5c07b"

[colors.cursor]
cursor = "0xabb2bf"
text = "0x282c34"

[colors.normal]
black = "0x282c34"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xabb2bf"
yellow = "0xe5c07b"

[colors.primary]
background = "0x282c34"
foreground = "0xabb2bf"

[cursor]
style = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[window]
decorations = "full"
dynamic_padding = true

[window.dimensions]
columns = 85
lines = 20

[window.padding]
x = 6
y = 0

[general]
live_config_reload = true
