#! /bin/sh

"$HOME"/.config/scripts/start_programs.sh &

bspc config border_width          0
bspc config window_gap            6

bspc config split_ratio           0.60
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc config center_pseudo_tiled   true

# Wal colors
. "$HOME"/.cache/wal/colors.sh
bspc config normal_border_color   "$color8"
bspc config active_border_color   "$color2"
bspc config focused_border_color  "$color7"
bspc config presel_feedback_color "$color7"

# Auto positioning
bspc rule -a VSCodium desktop='^2'
bspc rule -a IntelliJ desktop='^2'
bspc rule -a CLion desktop='^2'

bspc rule -a Firefox desktop='^3'
bspc rule -a Tor Browser desktop='^3'

bspc rule -a TelegramDesktop desktop='^4'

bspc rule -a spotify desktop='^5'

# Swallow
#pgrep bspswallow.sh || bspswallow.sh &

# Auto float
bspc rule -a Alacritty:dropdown_update state=floating
bspc rule -a Alacritty:dropdown_conn state=floating
bspc rule -a Alacritty:dropdown_terminal state=floating
bspc rule -a Zathura state=tiled
