#! /bin/sh

sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width          2
bspc config window_gap            12

bspc config split_ratio           0.60
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc config center_pseudo_tiled   true

"$HOME"/.config/scripts/start_programs.sh &

 # Wal colors
 . "$HOME"/.cache/wal/colors.sh
 bspc config normal_border_color   "$color8"
 bspc config active_border_color   "$color2"
 bspc config focused_border_color  "$color7"
 bspc config presel_feedback_color "$color7"

