#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

function setup_space {
  local idx="$1"
  local name="$2"
  local space=
  space=$(yabai -m query --spaces --space "$idx")
  if [ -z "$space" ]; then
    yabai -m space --create
  fi
  yabai -m space "$idx" --label "$name"
}

setup_space 1 manage
setup_space 2 emacs
setup_space 3 web
setup_space 4 other

yabai -m config layout bsp

yabai -m config window_placement first_child
yabai -m config window_placement second_child

GAPS=5
yabai -m config top_padding    $GAPS
yabai -m config bottom_padding $GAPS
yabai -m config left_padding   $GAPS
yabai -m config right_padding  $GAPS
yabai -m config window_gap     $GAPS

yabai -m config mouse_modifier cmd
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

yabai -m config focus_follows_mouse autofocus
yabai -m config mouse_follows_focus on
