name: xmonad-<yourname>
version: 0.1.0
synopsis: xmonad setting
github: <yourname>/.xmonad
author: <yourname>
maintainer: <youremail>@example.com
copyright: © <yourname>
license: MIT
dependencies:
  - X11
  - base
  - xmonad
  - xmonad-contrib
executables:
  xmonad:
    main: xmonad.hs
    ghc-options:
      - -Wall
      - -fwarn-tabs
      - -threaded
      - -O2
      - -with-rtsopts=-N4
