#! /bin/bash

startGnome() {
  XDG_SESSION_TYPE="wayland"
  dbus-run-session -- gnome-shell --display-server --wayland
}

startXMonad() {
  startx $HOME/.xinitrc xmonad
}

read -p "Session: " session
case $session in
  xmonad) startXMonad;;
  gnome) startGnome;;
  none) ;;
  *) startXMonad;;
esac


